services:
  app:
    build:
      context: docker
      dockerfile: Dockerfile.prod
    container_name: expense-tracker-app
    volumes:
      - .:/var/www/
    depends_on:
      - db
    networks:
      - expense-track
  db:
    image: postgres:15
    container_name: expense-tracker-db
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports:
      - "5436:5432"
    volumes:
      - expense-track:/var/lib/postgresql/data
    networks:
      - expense-track

  nginx:
    image: nginx:alpine
    container_name: expense-tracker-nginx
    ports:
      - "85:80"
    volumes:
      - .:/var/www/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - expense-track

volumes:
  expense-track:

networks:
  expense-track:

